# Generated by Django 2.2.3 on 2019-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190724_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
