# Generated by Django 2.2.3 on 2019-07-29 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190729_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 15, 30, 7, 213960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 15, 30, 7, 213960, tzinfo=utc)),
        ),
    ]
