# Generated by Django 2.2.3 on 2019-07-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190729_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
