# Generated by Django 2.2.3 on 2019-07-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190729_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
    ]
